// Generated by CoffeeScript 1.9.0
$(function() {
  var $block, $frame, $list, bootstrapcss, feedback, html, htmlBlock;
  $frame = $("#feedback");
  if ($frame.length === 0) {
    return;
  }
  bootstrapcss = $('link[href*="bootstrap.min.css"]');
  if (bootstrapcss.length === 0) {
    $("<link />").attr("rel", "stylesheet").attr("href", "http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css").prependTo("head");
  }
  html = "";
  html += '<div id="feedback">';
  html += '    <div class="loading">Loading feedbacks...</div>';
  html += '    <ol></ol>';
  html += '    <form>';
  html += '        <div class="wait">';
  html += '            <span>Please wait a while for me to submit your feedback.</span>';
  html += '        </div>';
  html += '        <div class="form">';
  html += '            <h3>Add Feedback</h3>';
  html += '            <div class="form-group">';
  html += '                <label>Description</label>';
  html += '                <input class="form-control" type="text" name="description" />';
  html += '            </div>';
  html += '            <div class="form-group">';
  html += '                <label>Name</label>';
  html += '                <input class="form-control" type="text" name="name" />';
  html += '            </div>';
  html += '            <div class="form-group text-right">';
  html += '                <button class="btn btn-success">Submit</button>';
  html += '            </div>';
  html += '        </div>';
  html += '    </form>';
  html += '    <li class="lineblock">';
  html += '        <span class="text description"></span>';
  html += '        <span class="text actions">';
  html += '            <button class="btn btn-success btn-xs complete">';
  html += '                Complete';
  html += '            </button>';
  html += '            <button class="btn btn-warning btn-xs uncomplete">';
  html += '                Uncomplete';
  html += '            </button>';
  html += '            <button class="btn btn-danger btn-xs delete">';
  html += '                Delete';
  html += '            </button>';
  html += '        </span>';
  html += '        <span class="text name"></span>';
  html += '    </li>';
  html += '</div>';
  htmlBlock = $(html);
  $frame.html(htmlBlock.html());
  $list = $frame.find("> ol");
  $block = $frame.find("> li.lineblock");
  feedback = function(data) {
    var dfd;
    data.identifier = $frame.data("identifier");
    return dfd = $.ajax({
      url: "api/feedback.php",
      type: "post",
      data: data,
      dataType: "json"
    });
  };
  $frame.on("submit", "> form", function(event) {
    var description, form, name;
    event.preventDefault();
    form = $(this);
    form.find("button").trigger("blur");
    form.addClass("submitting");
    description = form.find("input[name=description]");
    name = form.find("input[name=name]");
    return feedback({
      description: description.val(),
      name: name.val(),
      mode: "add"
    }).done(function(response) {
      var block;
      block = $block.clone();
      block.attr("data-id", response.id);
      block.find(".description").html(description.val());
      block.find(".name").html(name.val());
      block.appendTo($list);
      description.val("");
      name.val("");
      return form.removeClass("submitting");
    });
  });
  $frame.on("click", ".complete", function(event) {
    var block, button, id;
    button = $(this);
    block = button.parents(".lineblock");
    block.addClass("completed");
    id = block.data("id");
    return feedback({
      id: id,
      mode: "complete"
    });
  });
  $frame.on("click", ".uncomplete", function(event) {
    var block, button, id;
    button = $(this);
    block = button.parents(".lineblock");
    block.removeClass("completed");
    id = block.data("id");
    return feedback({
      id: id,
      mode: "uncomplete"
    });
  });
  $frame.on("click", ".delete", function(event) {
    var block, button, id;
    button = $(this);
    block = button.parents(".lineblock");
    block.remove();
    id = block.data("id");
    return feedback({
      id: id,
      mode: "delete"
    });
  });
  return feedback({
    mode: "load"
  }).done(function(response) {
    $frame.addClass("loaded");
    return $.each(response, function(i, row) {
      var block;
      block = $block.clone();
      block.attr("data-id", row.id);
      block.find(".description").html(row.description);
      block.find(".name").html(row.name);
      if (row.state) {
        block.addClass("completed");
      }
      return block.appendTo($list);
    });
  });
});
